version: '3.8' # Use a recent Docker Compose file format version

services:
  neo4j:
    image: neo4j:5 # You specified version 5, use the exact tag if needed (e.g., neo4j:5.20.0)
    container_name: neo4j-cpg # A memorable name for your container
    ports:
      - 7474:7474 # Neo4j Browser
      - 7687:7687 # Bolt protocol (for drivers and tools)
    environment:
      # Authentication
      - NEO4J_AUTH=neo4j/password # IMPORTANT: Change 'password' to a strong, secure password

      # Neo4j Memory Configuration (Adjust these values based on your needs)
      # These values are passed as environment variables, which the Neo4j Docker image
      # automatically maps to the neo4j.conf settings.
      # Units: 'm' for MB, 'g' for GB (e.g., '2g', '512m')
      - NEO4J_server_memory_heap_initial__size=2g # Initial JVM heap size
      - NEO4J_server_memory_heap_max__size=2g    # Maximum JVM heap size
#      - NEO4J_server_memory_pagecache__size=512m   # Amount of memory for caching graph data (off-heap)
      - NEO4J_dbms_memory_transaction_total_max=1g
#      - NEO4J_dbms_memory_transaction_max=512m

      # Plugins: Enable APOC
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.* # Required for APOC procedures

    # Volume for data persistence (highly recommended)
    # This ensures your graph data persists even if the container is removed.
#    volumes:
#      - ./data:/data # Mounts a local 'data' directory to the container's data directory
#      - ./logs:/logs # Mounts a local 'logs' directory for Neo4j logs
#      - ./import:/var/lib/neo4j/import # Optional: for importing data into Neo4j
#      - ./conf:/conf # Optional: for custom neo4j.conf file, if you prefer that over environment variables

    restart: unless-stopped # Automatically restart the container unless manually stopped
